# Generated by Django 3.2 on 2021-06-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '__first__'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('user_rating', models.FloatField(null=True)),
                ('user_review', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Waiting', 'Waiting'), ('Processing', 'Processing')], max_length=20)),
                ('cab_type', models.CharField(choices=[('Motorbike', 'Motorbike'), ('Car', 'Car'), ('Every types', 'Every types')], default='Motorbike', max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_DRIVER_TRIP', to='driver.driver')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_END_LOCATION_TRIP', to='location.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_START_LOCATION_TRIP', to='location.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_USER_TRIP', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
