# Generated by Django 3.2 on 2021-06-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('cab_type', models.CharField(choices=[('Motorbike', 'Motorbike'), ('Car', 'Car')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Busy', 'Busy'), ('Offline', 'Offline')], max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('license_driver', models.CharField(max_length=12)),
                ('cab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.cab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
