# Generated by Django 3.2 on 2021-07-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('northeast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_NORTHEAST', to='location.location')),
                ('southwest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_SOUTHEST', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyline', models.TextField()),
                ('duration', models.CharField(max_length=10)),
                ('distance', models.CharField(max_length=10)),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.bound')),
            ],
        ),
    ]
