# Generated by Django 3.2 on 2021-06-12 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('notice_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('receiver_type', models.SmallIntegerField(null=True)),
                ('receiver', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
