# Generated by Django 3.2 on 2021-07-08 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'System'), (1, 'User cancel the trip'), (2, 'Driver accept the trip'), (3, 'Driver cancel the trip'), (4, 'The trip completed')], null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_USER_NOTIFICATION', to=settings.AUTH_USER_MODEL),
        ),
    ]
